### ISSUE TITLE
Remove timestamp from date fields

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-zap-opendata#14]

**Comment by SashaWeinstein** [comment]
@AmandaDoyle is it ok if this change is made to the data sent to bigquery and data library? Or should it only be changed for the open data sent to edm-publishing

**Comment by AmandaDoyle** [comment]
@SashaWeinstein  It's 100% okay if this change is made in the data being sent to bigquery if that's the easiest place to make the change.  It's my understanding that there is no business use case for the time.
