### ISSUE TITLE
Possible process error: no ZAP output on DO after 2023-02-13

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/db-zap-opendata#37]
We discovered a possible issue with the ZAP data delivery to Digital Ocean. 
When prepping monthly Open Data, we pull the latest ZAP dataset from this location on [DO](https://cloud.digitalocean.com/spaces/edm-publishing?i=266877&path=db-zap%2F). It looks like typically these datasets are updated weekly by a DE process, but the last dataset currently available is from 2/13/2023.

Tagging @NYCPlanning/data-engineering and @croswell81

**Comment by fvankrieken** [comment]
Weird - nothing in the repo has changed for a while, the weekly jobs seem to have just stopped running, silently

https://github.com/NYCPlanning/db-zap-opendata/actions

Any global changes to our github organization last month that could have caused this?

**Comment by damonmcc** [comment]
screenshot from the Action section after clicking on Weekly Export:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/7444289/227538344-d6a52ecf-e36e-477d-b4f7-3231944f338b.png">

**Comment by fvankrieken** [comment]
Was about to post the same. Fun. Want to go ahead and enable? Let's see if we can bump that (or have github bot do something to keep the repo active every month or something)

**Comment by fvankrieken** [comment]
Re-enabled and triggered a manual run now
