### ISSUE TITLE
Fixing ZAP data column order and add steps to copy dataset to BigQuery

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-zap-opendata#6]
## Problem:
The ZAP data dump we get from CRM is generated from a collection of API responses in JSON format. JSON responses are tricky because there's no set order for the keys. This will eventually impact on data import at the BigQuery step, because BigQuery always expects a fixed schema order from the csvs.

## Goal:
1. find a way to fix the column order of the csvs outputted to data library
2. Add an additional step to load data into BigQuery. (using a bq command)

### Task 1:
The python package itself its very complicated, it deals with crm authentication and there are databases involved. So I wouldn't recommend digging too deep into python to solve this.
we can actually very conveniently use the `sql` section of the template files under `db-zap-opendata/templates/` to fix the column order. e.g.
```sql
SELECT 
_odata_etag
,_dcp_leadaction_value
,dcp_needsintervention
,dcp_totalprecertonholddays_date
,dcp_name
,dcp_totalprecertonholddays_state
,dcp_lastmilestonedate
,dcp_nepareview
.....
FROM @filename
```
You can find the schema definition for these tables in the `db-zap-opendata/schemas` folder. 

So you will have to update the template files for the following datasets (you can check off the boxes into indicate progress)
- [ ] dcp_projects
- [ ] dcp_projectactions
- [ ] dcp_projectbbls
- [ ] dcp_dcpprojectteams
- [ ] dcp_communityboarddispositions
- [ ] dcp_projectactionbbls
- [ ] dcp_projectmilestones

Make sure you include all template file changes in one pull request and assign @SPTKL  for review

I created a little python script thing to convert a bigquery schema file into a select sql statement that complies with data library conventions. Feel free to use it. 
```python
import json
import sys

def convert_to_sql(filename):
    with open(filename) as f:
        schema = json.load(f)
    cols = [s['name'] for s in schema]
    sql = 'SELECT ' + '\n,'.join(cols) + '\nFROM @filename'
    with open(filename.replace('.json', '.sql'), 'w') as f:
        f.write(sql)

if __name__ == '__main__':
    filename = sys.argv[1]
    convert_to_sql(filename)
```

### Task 2: 
Once task 1 is fixed, we are ready to move ahead and load these tables into data-library, then BigQuery. Please refer to our [current workflow file](https://github.com/NYCPlanning/db-zap-opendata/blob/main/.github/workflows/export.yml) to see how we are archiving data to data library. 

> For context, we are currently using a matrix strategy to run multiple similar workflows at the same time ([read more](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix))

Ideally, your implementation will add one or two additional steps following `Archive to data library - CSV`. So that everytime after the csvs are archived in data library, they will also be pushed to BigQuery. 

## Resources: 
How to set up google cloud sdk in github actions:

https://github.com/NYCPlanning/db-cpdb/blob/2aa17760e8c4dd55e4a079c139e2e08c07c9c658/.github/workflows/spending.yml#L38-L43

**Comment by SSimon16** [comment]
@SPTKL do I need to be given access to push to db-zap-opendata? Or, should I fork the repository first? I'm getting a permission error when I try to push.

**Comment by SPTKL** [comment]
you now have permission @SSimon16 @micrittenden
